Task Interfaces
quwee/Go-internship pull request #4
Opened 2024-05-10 01:02 UTC by quwee

2024-05-22 14:22 UTC, stassanakoyeu requested changes

2024-05-22 15:10 UTC, quwee commented on interfaces/exercise2/area.go
> +		if *radiusArgPtr < 0 {
no, it can't, I added check for this

2024-05-22 15:10 UTC, quwee commented on interfaces/exercise2/area.go
> +		if *heightArgPtr < 0 {
no, it can't, I added check for this

2024-05-23 06:47 UTC, stassanakoyeu approved these changes

2024-05-23 11:12 UTC, merged